### ISSUE TITLE
Custom newsletter settings do not work

### ISSUE THREAD

**Issue by cappie15** [GauthierNelkinsky/ShipShipShip#15]
The Newsletter Management settings page fails to load due to a JavaScript error: `ReferenceError: newsletterEnabled is not defined.` As a result, newsletter configuration cannot be used when sending newsletters.

**Symptoms**
- Settings panel shows a red banner: “Failed to load newsletter settings”.
- Browser console logs: ReferenceError: newsletterEnabled is not defined.
- Error repeats during async initialization flow.
- Newsletter History loads correctly.
- Email Templates load correctly.

**Expected behavior**
- A custom e-mailtemplate which is saved and shows in admin-section, is used when (auto)sending newsletter

**Actual behavior**
- custom e-mailtemplate is ignored and message with the default template was sent. l.

**Likely root cause (hypothesis)**
1. Backend response no longer includes the newsletterEnabled field.
2. Field was renamed (e.g., isNewsletterEnabled), but the frontend was not updated.
3. A migration removed or changed the field, causing a mismatch between frontend expectations and backend schema.
4. Frontend destructuring fails because the property does not exist on the returned object.

**Comment by GauthierNelkinsky** [comment]
Version 1.3.2 should have fixed the issue !

I also fixed the "Unsubscribe" URL to make sure that the users can unsubscribe to the newsletter properly.

**Comment by cappie15** [comment]
@GauthierNelkinsky; This is not resolved: I just sent another one of our weekly newsletters using the autosend feature in “Newsletter Automation.” According to the template, the email subject should be “🎉 New release: {{event_name}},” but the actual subject is “Release: v25.51 – Release notes” (which I believe is the default). Additionally, the email body includes event_content, even though this is not part of my template.

<img width="2942" height="888" alt="Image" src="https://github.com/user-attachments/assets/77020a55-fb21-4946-bbf6-ca29b55bdee2" />

**Comment by GauthierNelkinsky** [comment]
Have you tried with the latest update?
I made some more changes yesterday with version 1.3.4.

When I test it, the newsletter works fine, even when it is sent automatically. (See screenshots)

<img width="936" height="632" alt="Image" src="https://github.com/user-attachments/assets/8cd7b722-0fe7-4b7a-b3b6-43b77351a56e" />

---

<img width="750" height="179" alt="Image" src="https://github.com/user-attachments/assets/540b082f-3484-4bb6-9901-dcff770125a5" />
